In [1]:
import pandas as pd
import numpy as np

In [55]:
#extract table columns from a excel dataset based on column names, outputs a df

def Column_Selector():
    
    file_path = str(input("Input file name or path: "))
    
    load_excel = pd.ExcelFile(file_path)
    
    print("Sheets available in this file: ", load_excel.sheet_names)
    
    sheet_name = str(input("Which sheet would you like to access?: "))
    
    overall_df = pd.read_excel(file_path, sheet_name=sheet_name)
        
    print("These are the columns in this file: ", list(overall_df))
    
    select_columns = input("Which columns would you like to select? Type in name of column separated by a comma. (e.g. Default Weights, Q136): ")
    
    column_list = select_columns.replace(", ",",").split(",")
    
    temp_df = overall_df[column_list]
    
    for i in column_list:
        rename = str(input(f'What would you like to rename {i}: '))
        temp_df.rename(columns = {i:rename}, inplace = True)
    
    return temp_df

In [94]:
df = Column_Selector()

Input file name or path: Nest_US_Video_Verbatims_Q2-Q4.xlsx
Sheets available in this file:  ['Q2 2019 - 19Q2_015 (1)', 'Q2 2019 - 19Q2_015 (2)', 'Q3 2019 - 19Q2_016', 'Q3 2019 - 12Q3_011', 'Q4 2019 - 19Q3_076', 'Q4 2019 - 19Q4_011', 'Q4 2019 - 19Q4_026', 'Q4 2019 - 19Q4_044', 'Q4 2019 - 19Q4_059']
Which sheet would you like to access?: Q4 2019 - 19Q4_059
These are the columns in this file:  ['Creative', 'Q170', 'Q171', 'Q172']
Which columns would you like to select? Type in name of column separated by a comma. (e.g. Default Weights, Q136): Creative, Q170, Q171, Q172
What would you like to rename Creative: creative
What would you like to rename Q170: Takeaways
What would you like to rename Q171: Likes
What would you like to rename Q172: Dislikes

In [99]:
df

,Creative2,Takeaways,Likes,Dislikes
0,(C) Frozen Stories,Easy to connect smart technology,The innovation,Nothing
1,(B) Frozen Read Along,It's innovative,I liked the Frozen characters.,Nothing was disliked
2,(A) Control,NaN,NaN,NaN
3,(A) Control,NaN,NaN,NaN
4,(B) Frozen Read Along,Offers so many features,That it showed scenes from frozen2,Nothing
...,...,...,...,...
745,(C) Frozen Stories,It can tell you stories,I like the technology,Frozen
746,(C) Frozen Stories,It can tell stories,That it can appeal to multiple age groups,To much focused on frozen took away from the a...
747,(C) Frozen Stories,Awesome,Great,Good
748,(A) Control,NaN,NaN,NaN
749,(A) Control,NaN,NaN,NaN

In [96]:
type(df)

pandas.core.frame.DataFrame

In [106]:
def Creative_Selector(dataframe):
    
    if isinstance(dataframe, pd.DataFrame):
        print("These are the columns in this file: ", list(dataframe))
        creative_column = str(input("Which is the creative column?: "))
        if creative_column not in list(dataframe):
            return "That column is not in the dataframe!"
        else:
            dataframe.rename(columns={creative_column:'Creative'}, inplace=True)
            dataframe_group = dict(tuple(dataframe.groupby('Creative')))
            creative_list = dataframe.Creative.unique()
            print("There are the unique creatives in this dataset: ", list(creative_list))
            selected_creative = str(input("Which creative would you like to analyze?: "))
            selected_creative_df =  dataframe_group[selected_creative]     
            return selected_creative_df
    else:
        return print("You have not passed a pandas dataframe to the function!")

In [107]:
Frozen_Stories = Creative_Selector(df)

These are the columns in this file:  ['Creative', 'Takeaways', 'Likes', 'Dislikes']
Which is the creative column?: Creative
There are the unique creatives in this dataset:  ['(C) Frozen Stories', '(B) Frozen Read Along', '(A) Control']
Which creative would you like to analyze?: (C) Frozen Stories

In [97]:
test = 'creative'
df.rename(columns={test:'Creative2'}, inplace=True)
print(df)

None

In [103]:
df

,Creative,Takeaways,Likes,Dislikes
0,(C) Frozen Stories,Easy to connect smart technology,The innovation,Nothing
1,(B) Frozen Read Along,It's innovative,I liked the Frozen characters.,Nothing was disliked
2,(A) Control,NaN,NaN,NaN
3,(A) Control,NaN,NaN,NaN
4,(B) Frozen Read Along,Offers so many features,That it showed scenes from frozen2,Nothing
...,...,...,...,...
745,(C) Frozen Stories,It can tell you stories,I like the technology,Frozen
746,(C) Frozen Stories,It can tell stories,That it can appeal to multiple age groups,To much focused on frozen took away from the a...
747,(C) Frozen Stories,Awesome,Great,Good
748,(A) Control,NaN,NaN,NaN
749,(A) Control,NaN,NaN,NaN

In [108]:
Frozen_Stories

,Creative,Takeaways,Likes,Dislikes
0,(C) Frozen Stories,Easy to connect smart technology,The innovation,Nothing
7,(C) Frozen Stories,None,None,None
12,(C) Frozen Stories,Don't know,Not sure,Don't know
17,(C) Frozen Stories,Nothing,Nothing special,Boring
26,(C) Frozen Stories,How good the product is,I liked everything about it,I like everything
...,...,...,...,...
741,(C) Frozen Stories,Call a certain name and itâ€™ll identify quickly,Itâ€™s multifunctional,NaN
742,(C) Frozen Stories,I love it good,Everything I loved it,Good to see it's good
745,(C) Frozen Stories,It can tell you stories,I like the technology,Frozen
746,(C) Frozen Stories,It can tell stories,That it can appeal to multiple age groups,To much focused on frozen took away from the a...
747,(C) Frozen Stories,Awesome,Great,Good

In [109]:
Frozen_Stories = Creative_Selector(Column_Selector())

Input file name or path: Nest_US_Video_Verbatims_Q2-Q4.xlsx
Sheets available in this file:  ['Q2 2019 - 19Q2_015 (1)', 'Q2 2019 - 19Q2_015 (2)', 'Q3 2019 - 19Q2_016', 'Q3 2019 - 12Q3_011', 'Q4 2019 - 19Q3_076', 'Q4 2019 - 19Q4_011', 'Q4 2019 - 19Q4_026', 'Q4 2019 - 19Q4_044', 'Q4 2019 - 19Q4_059']
Which sheet would you like to access?: Q4 2019 - 19Q4_059
These are the columns in this file:  ['Creative', 'Q170', 'Q171', 'Q172']
Which columns would you like to select? Type in name of column separated by a comma. (e.g. Default Weights, Q136): Creative, Q170, Q171, Q172
What would you like to rename Creative: Creative
What would you like to rename Q170: Takeaways
What would you like to rename Q171: Likes
What would you like to rename Q172: Dislikes
These are the columns in this file:  ['Creative', 'Takeaways', 'Likes', 'Dislikes']
Which is the creative column?: Creative
There are the unique creatives in this dataset:  ['(C) Frozen Stories', '(B) Frozen Read Along', '(A) Control']
Which creative would you like to analyze?: (C) Frozen Stories

def Verbatim_Cleaner(dataframe):
    print("These are the columns in the dataframe.: ", list(dataframe))
    verbatim_column = input("Which column contains the verbatims for analysis?")

In [112]:
df3 = 'j'
Creative_Selector(df3)

You have not passed a pandas dataframe to the function!